### ISSUE TITLE
Bug: Error: libcuda.so: cannot open shared object file

### ISSUE THREAD

**Issue by hamid98reza** [tensorflow/hub#884]
### What happened?

Hi.
I am using Asus, windows 11 with RTX 3050 cuda 12.1.
 I used wsl2 with miniconda for setting up the tensorflow 2.12 installation as It has mentioned in the official site.
 installed :--> conda install -c conda-forge cudatoolkit=11.8.0   and   pip install nvidia-cudnn-cu11==8.6.0.163

and the path was set as it has been defined there:
-- mkdir -p $CONDA_PREFIX/etc/conda/activate.d

--echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh

--echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh

then installed tensorflow 2.12* and the gpu verification was fine .

then I installed ultlralytics to work with YOLOv8 but when I want to use it, I encouter the following error in wsl terminal.(it may be worth noting to mention that ultralytics installed nvidia-cudnn-cu11 == 8.5.0.96 and I think uninstalled the previous version nvidia-cudnn-cu11==8.6.0.163).

please help.  

### Relevant code

```python
(tensor) root@DESKTOP-7UHKVHO:/mnt/c/Users/save2/yol1/yol12# yolo mode=predict task=detect model=yolov8l.pt show=True source=m
```

### Relevant log output

```shell
Ultralytics YOLOv8.0.89 🚀 Python-3.9.16 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory
Aborted
```

### tensorflow_hub Version

other (please specify)

### TensorFlow Version

other (please specify)

### Python Version

3.x

### OS

Windows

**Comment by hamid98reza** [comment]
by doing the following solution :

> cd \Windows\System32\lxss\lib
> del libcuda.so
> del libcuda.so.1
> mklink libcuda.so libcuda.so.1.1
> mklink libcuda.so.1 libcuda.so.1.1

from : https://stackoverflow.com/questions/76016645/tensorflow-2-12-could-not-load-library-libcudnn-cnn-infer-so-8-in-wsl2

my problem solved .

**Comment by singhniraj08** [comment]
@hamid98reza,

Since you have found a solution, requesting you to close this issue. Thank you!

**Comment by singhniraj08** [comment]
Closing this due to inactivity. Please take a look into the answers provided above, feel free to reopen and post your comments(if you still have queries on this). Thank you!
